"""OWL BASIC ``dotnet`` backend.

Emits textual CIL (``.il``), assembles it with ``ilasm`` into a .NET assembly,
and runs on the CLR or Mono against the OwlRuntime runtime library. This is the
first backend built on the new textual-CIL approach, replacing the legacy
in-process ``System.Reflection.Emit`` code generator that required IronPython.
"""

import logging
import re
import shutil
import subprocess
from pathlib import Path

from owl_basic.codegen.backend import Backend as BackendBase, Program

logger = logging.getLogger(__name__)

_NON_IDENT = re.compile(r"[^A-Za-z0-9_]")


class Backend(BackendBase):
    """Generate a .NET executable by emitting textual CIL and assembling it with
    ilasm. Runs on the .NET CLR or Mono, against the OwlRuntime runtime library.
    """

    def generate(self, program: Program, output_dirpath, options=None) -> Path:
        output_dirpath = Path(output_dirpath)
        il_text = self.emit_il(program)
        il_filepath = output_dirpath / (self._assembly_name(program) + ".il")
        il_filepath.write_text(il_text, encoding="utf-8")
        logger.debug("Wrote CIL to %s", il_filepath)
        return il_filepath

    def emit_il(self, program: Program) -> str:
        """Render *program* as textual CIL.

        SKELETON: emits a structurally-valid, runnable assembly with an empty
        entry point. Lowering of ``program.ordered_basic_blocks`` into real CIL
        is the next increment.
        """
        name = self._assembly_name(program)
        lines = [
            "// Generated by OWL BASIC (dotnet backend)",
            ".assembly extern mscorlib { }",
            ".assembly " + name + " { }",
            ".module " + name + ".exe",
            "",
            ".method static void Main() cil managed",
            "{",
            "    .entrypoint",
            "    .maxstack 8",
            "    ret",
            "}",
            "",
        ]
        return "\n".join(lines)

    def assemble(self, il_filepath, exe_filepath=None) -> Path:
        """Assemble a ``.il`` file into a .NET executable with ``ilasm``.

        Kept separate from :meth:`generate` because ``ilasm`` is an external
        toolchain dependency that need not be present merely to produce the CIL
        text (which is what the unit tests exercise).
        """
        il_filepath = Path(il_filepath)
        if exe_filepath is None:
            exe_filepath = il_filepath.with_suffix(".exe")
        ilasm = shutil.which("ilasm")
        if ilasm is None:
            raise FileNotFoundError(
                "ilasm not found on PATH (install Mono, or the .NET ILAsm tool)"
            )
        subprocess.run(
            [ilasm, "/exe", "/output:" + str(exe_filepath), str(il_filepath)],
            check=True,
            capture_output=True,
            text=True,
        )
        return exe_filepath

    @staticmethod
    def _assembly_name(program: Program) -> str:
        return _NON_IDENT.sub("_", program.name) or "owl_program"
