"""Textual CIL emitter for the dotnet backend.

Lowers an analysed :class:`~owl_basic.codegen.backend.Program` to textual CIL
(``.il``) that the CoreCLR ``ilasm`` assembles into a .NET assembly. Output is
printed by calling into the OwlRuntime runtime library, whose default screen
mode is the headless raw console (stdout).

This is the first, deliberately small slice of the lowering — enough to compile
print/arithmetic programs such as six_times_seven. It reuses the opcode
knowledge of the legacy reflection-based ``codegen/clr/cil_visitor.py`` but
writes mnemonics as text instead of driving ``System.Reflection.Emit``.
"""

import re

from owl_basic.exceptions import OwlBasicError
from owl_basic.owltyping.type_system import (
    ByteOwlType,
    FloatOwlType,
    IntegerOwlType,
    StringOwlType,
)

# A curated slice of the OwlRuntime "signature manifest": the textual CIL
# signatures of the BasicCommands methods we call. This will be generated from
# OwlRuntime.dll (via monodis / reflection) rather than hand-listed; for now the
# handful we emit are spelled out. See BasicCommands in the OwlRuntime project.
_RUNTIME = "[OwlRuntime]OwlRuntime.BasicCommands"

_PRINT_NEWLINE = "call void {0}::NewLine()".format(_RUNTIME)

# Map a textual CIL operator mnemonic onto each binary arithmetic AST node.
_BINARY_OPS = {
    "Plus": "add",
    "Minus": "sub",
    "Multiply": "mul",
    "Divide": "div",
}


class CodeGenerationError(OwlBasicError):
    """Raised when the emitter meets an AST node it cannot yet lower."""


# Map an OwlType onto the CIL type used for a local / runtime argument. Order
# matters: ChannelOwlType is an IntegerOwlType, ByteOwlType is distinct.
_IL_TYPES = [
    (StringOwlType, "string"),
    (FloatOwlType, "float64"),
    (ByteOwlType, "int32"),
    (IntegerOwlType, "int32"),
]


def _il_type(owl_type):
    for cls, il in _IL_TYPES:
        if isinstance(owl_type, cls):
            return il
    return "int32"


def emit_program(program, assembly_name):
    """Render *program* as a complete textual CIL assembly."""
    emitter = _MethodEmitter()
    blocks_by_entry = program.ordered_basic_blocks or {}
    # Only the main program entry point is lowered in this first slice.
    for block in blocks_by_entry.get("__owl__main", []):
        for statement in block.statements:
            emitter.lower_statement(statement)
    emitter.finish()

    body = "\n".join("        " + line for line in emitter.lines)
    return _ASSEMBLY_TEMPLATE.format(
        name=assembly_name, locals=emitter.locals_declaration(), body=body
    )


_ASSEMBLY_TEMPLATE = """\
// Generated by OWL BASIC (dotnet backend)
.assembly extern System.Runtime {{ }}
.assembly extern OwlRuntime {{ }}
.assembly {name} {{ }}
.module {name}.dll

.method static void Main() cil managed
{{
    .entrypoint
    .maxstack 8
{locals}{body}
        ret
}}
"""


class _MethodEmitter:
    def __init__(self):
        self.lines = []
        self._local_slots = {}   # variable identifier -> local slot index
        self._local_types = []   # CIL type string, indexed by slot

    def emit(self, text):
        self.lines.append(text)

    def _local_slot(self, identifier, owl_type):
        """Return the local slot for *identifier*, allocating one on first use."""
        if identifier not in self._local_slots:
            self._local_slots[identifier] = len(self._local_types)
            self._local_types.append(_il_type(owl_type))
        return self._local_slots[identifier]

    def locals_declaration(self):
        """Render the method's ``.locals init`` block (empty if no locals)."""
        if not self._local_types:
            return ""
        entries = ",\n".join(
            "        %s V_%d" % (il_type, slot)
            for slot, il_type in enumerate(self._local_types)
        )
        return "    .locals init (\n%s\n    )\n" % entries

    def finish(self):
        # The assembly template appends the trailing `ret`; nothing to do yet.
        pass

    # -- statements ---------------------------------------------------------

    def lower_statement(self, node):
        name = type(node).__name__
        handler = getattr(self, "_stmt_" + name, None)
        if handler is None:
            raise CodeGenerationError("Cannot lower statement node %r" % name)
        handler(node)

    def _stmt_Print(self, node):
        for print_item in node.printList:
            item = print_item.item
            self.lower_expression(item)
            self.emit(self._print_call(item))
        # PRINT terminates the line unless suppressed by a trailing separator
        # (`;`/`,`), which this first slice does not yet model.
        self.emit(_PRINT_NEWLINE)

    def _stmt_ScalarAssignment(self, node):
        target = node.lValue
        if type(target).__name__ != "Variable":
            # Indirection / indexed / pseudo-variable l-values come later.
            raise CodeGenerationError(
                "Cannot lower assignment to %r l-value" % type(target).__name__
            )
        self.lower_expression(node.rValue)
        slot = self._local_slot(target.identifier, target.actualType)
        self.emit("stloc V_%d" % slot)

    def _stmt_Rem(self, node):
        # A comment generates no code.
        pass

    def _stmt_End(self, node):
        # Returning from Main ends the program; the template's trailing `ret`
        # also covers a program with no explicit END.
        self.emit("ret")

    # -- expressions --------------------------------------------------------

    def lower_expression(self, node):
        name = type(node).__name__
        if name in _BINARY_OPS:
            self.lower_expression(node.lhs)
            self.lower_expression(node.rhs)
            self.emit(_BINARY_OPS[name])
            return
        handler = getattr(self, "_expr_" + name, None)
        if handler is None:
            raise CodeGenerationError("Cannot lower expression node %r" % name)
        handler(node)

    def _expr_LiteralString(self, node):
        self.emit("ldstr " + _il_string(node.value))

    def _expr_LiteralInteger(self, node):
        self.emit("ldc.i4 %d" % int(node.value))

    def _expr_LiteralFloat(self, node):
        self.emit("ldc.r8 %r" % float(node.value))

    def _expr_Variable(self, node):
        slot = self._local_slot(node.identifier, node.actualType)
        self.emit("ldloc V_%d" % slot)

    # -- runtime call selection --------------------------------------------

    def _print_call(self, item):
        owl_type = getattr(item, "actualType", None)
        if isinstance(owl_type, StringOwlType):
            arg = "string"
        elif isinstance(owl_type, (IntegerOwlType, ByteOwlType)):
            arg = "int32"
        elif isinstance(owl_type, FloatOwlType):
            arg = "float64"
        else:
            # Fall back to the static node shape when the type is unresolved.
            arg = _arg_from_node(item)
        return "call void {0}::Print({1})".format(_RUNTIME, arg)


def _arg_from_node(node):
    name = type(node).__name__
    if name == "LiteralString":
        return "string"
    if name == "LiteralFloat":
        return "float64"
    # Integers and integer arithmetic.
    return "int32"


_ESCAPES = {"\\": "\\\\", '"': '\\"', "\n": "\\n", "\r": "\\r", "\t": "\\t"}


def _il_string(value):
    """Render a Python string as an ILAsm string literal."""
    out = []
    for ch in value:
        if ch in _ESCAPES:
            out.append(_ESCAPES[ch])
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append("\\%03o" % ord(ch))  # ILAsm octal escape
    return '"' + "".join(out) + '"'
