"""Textual CIL emitter for the dotnet backend.

Lowers an analysed :class:`~owl_basic.codegen.backend.Program` to textual CIL
(``.il``) that the CoreCLR ``ilasm`` assembles into a .NET assembly. Output is
printed by calling into the OwlRuntime runtime library, whose default screen
mode is the headless raw console (stdout).

This is the first, deliberately small slice of the lowering — enough to compile
print/arithmetic programs such as six_times_seven. It reuses the opcode
knowledge of the legacy reflection-based ``codegen/clr/cil_visitor.py`` but
writes mnemonics as text instead of driving ``System.Reflection.Emit``.
"""

import re

from owl_basic.exceptions import OwlBasicError
from owl_basic.owltyping.type_system import (
    ByteOwlType,
    FloatOwlType,
    IntegerOwlType,
    StringOwlType,
)

# A curated slice of the OwlRuntime "signature manifest": the textual CIL
# signatures of the BasicCommands methods we call. This will be generated from
# OwlRuntime.dll (via monodis / reflection) rather than hand-listed; for now the
# handful we emit are spelled out. See BasicCommands in the OwlRuntime project.
_RUNTIME = "[OwlRuntime]OwlRuntime.BasicCommands"

_PRINT_NEWLINE = "call void {0}::NewLine()".format(_RUNTIME)

# Map a textual CIL operator mnemonic onto each binary arithmetic AST node.
_BINARY_OPS = {
    "Plus": "add",
    "Minus": "sub",
    "Multiply": "mul",
    "Divide": "div",
}

# BBC BASIC's AND/OR/EOR are bitwise; with OWL booleans (0 / -1) they double as
# the logical connectives in conditions.
_LOGICAL_OPS = {
    "And": "and",
    "Or": "or",
    "Eor": "xor",
}

# Numeric relational operators, as CIL opcode sequences that leave an OWL
# boolean (0 / -1) on the stack. The trailing `neg` converts a CLR boolean
# (0 / 1) into BBC's 0 / -1; `<>`/`<=`/`>=` build on `ceq`/`clt`/`cgt`.
_RELATIONAL_OPS = {
    "Equal": ["ceq", "neg"],
    "NotEqual": ["ceq", "ldc.i4.1", "sub"],
    "LessThan": ["clt", "neg"],
    "GreaterThan": ["cgt", "neg"],
    "LessThanEqual": ["cgt", "ldc.i4.0", "ceq", "neg"],
    "GreaterThanEqual": ["clt", "ldc.i4.0", "ceq", "neg"],
}


class CodeGenerationError(OwlBasicError):
    """Raised when the emitter meets an AST node it cannot yet lower."""


# Map an OwlType onto the CIL type used for a local / runtime argument. Order
# matters: ChannelOwlType is an IntegerOwlType, ByteOwlType is distinct.
_IL_TYPES = [
    (StringOwlType, "string"),
    (FloatOwlType, "float64"),
    (ByteOwlType, "int32"),
    (IntegerOwlType, "int32"),
]


def _il_type(owl_type):
    for cls, il in _IL_TYPES:
        if isinstance(owl_type, cls):
            return il
    return "int32"


def emit_program(program, assembly_name):
    """Render *program* as a complete textual CIL assembly."""
    emitter = _MethodEmitter()
    blocks_by_entry = program.ordered_basic_blocks or {}
    # Only the main program entry point is lowered for now.
    emitter.lower_blocks(blocks_by_entry.get("__owl__main", []))
    emitter.finish()

    body = "\n".join("        " + line for line in emitter.lines)
    return _ASSEMBLY_TEMPLATE.format(
        name=assembly_name, locals=emitter.locals_declaration(), body=body
    )


# Statements that emit their own control transfer (or end the method), so the
# block they end needs no implicit fall-through branch generated for it.
_BRANCHING_STATEMENTS = frozenset(
    {"If", "OnGoto", "End", "ReturnFromProcedure", "ReturnFromFunction",
     "LongJump", "Run", "Raise"}
)


_ASSEMBLY_TEMPLATE = """\
// Generated by OWL BASIC (dotnet backend)
.assembly extern System.Runtime {{ }}
.assembly extern OwlRuntime {{ }}
.assembly {name} {{ }}
.module {name}.dll

.method static void Main() cil managed
{{
    .entrypoint
    .maxstack 8
{locals}{body}
        ret
}}
"""


class _MethodEmitter:
    def __init__(self):
        self.lines = []
        self._local_slots = {}   # variable identifier -> local slot index
        self._local_types = []   # CIL type string, indexed by slot

    def emit(self, text):
        self.lines.append(text)

    def _local_slot(self, identifier, owl_type):
        """Return the local slot for *identifier*, allocating one on first use."""
        if identifier not in self._local_slots:
            self._local_slots[identifier] = len(self._local_types)
            self._local_types.append(_il_type(owl_type))
        return self._local_slots[identifier]

    def locals_declaration(self):
        """Render the method's ``.locals init`` block (empty if no locals)."""
        if not self._local_types:
            return ""
        entries = ",\n".join(
            "        %s V_%d" % (il_type, slot)
            for slot, il_type in enumerate(self._local_types)
        )
        return "    .locals init (\n%s\n    )\n" % entries

    # -- basic blocks -------------------------------------------------------

    def lower_blocks(self, blocks):
        """Lower a routine's basic blocks (in topological order) with labels.

        Control flow is carried by the block-level CFG: each block gets a label,
        and a block whose single successor is not the next block in order ends
        with an explicit branch (otherwise it falls through).
        """
        self._block_index = {id(block): index for index, block in enumerate(blocks)}
        for index, block in enumerate(blocks):
            self.emit("%s:" % self._block_label(block))
            for statement in block.statements:
                self.lower_statement(statement)
            self._emit_fall_through(block, index)

    def _block_label(self, block):
        return "BB_%d" % self._block_index[id(block)]

    def _emit_fall_through(self, block, index):
        last = block.statements[-1] if block.statements else None
        if last is not None and type(last).__name__ in _BRANCHING_STATEMENTS:
            return  # the statement emitted its own control transfer
        successors = list(block.outEdges)
        if len(successors) == 1:
            successor = successors[0]
            if self._block_index.get(id(successor)) != index + 1:
                self.emit("br " + self._block_label(successor))

    def finish(self):
        # The assembly template appends the trailing `ret`; nothing to do yet.
        pass

    # -- statements ---------------------------------------------------------

    def lower_statement(self, node):
        name = type(node).__name__
        handler = getattr(self, "_stmt_" + name, None)
        if handler is None:
            raise CodeGenerationError("Cannot lower statement node %r" % name)
        handler(node)

    def _stmt_Print(self, node):
        for print_item in node.printList:
            item = print_item.item
            self.lower_expression(item)
            self.emit(self._print_call(item))
        # PRINT terminates the line unless suppressed by a trailing separator
        # (`;`/`,`), which this first slice does not yet model.
        self.emit(_PRINT_NEWLINE)

    def _stmt_ScalarAssignment(self, node):
        target = node.lValue
        if type(target).__name__ != "Variable":
            # Indirection / indexed / pseudo-variable l-values come later.
            raise CodeGenerationError(
                "Cannot lower assignment to %r l-value" % type(target).__name__
            )
        self.lower_expression(node.rValue)
        slot = self._local_slot(target.identifier, target.actualType)
        self.emit("stloc V_%d" % slot)

    def _stmt_If(self, node):
        # Flow analysis emptied the clauses into their own blocks; branch to them
        # by block, falling through where the layout allows (cf. the legacy CIL
        # visitor). The condition leaves an OWL boolean (0 / -1) on the stack.
        self.lower_expression(node.condition)
        true_statement = node.trueClause[0]
        false_targets = set(node.outEdges)
        false_targets.discard(true_statement)
        if len(false_targets) != 1:
            raise CodeGenerationError("IF with %d false targets" % len(false_targets))
        false_statement = next(iter(false_targets))

        this_index = self._block_index[id(node.block)]
        true_index = self._block_index[id(true_statement.block)]
        false_index = self._block_index[id(false_statement.block)]
        true_label = self._block_label(true_statement.block)
        false_label = self._block_label(false_statement.block)

        if true_index == this_index + 1:
            self.emit("brfalse " + false_label)          # fall through to true
        elif false_index == this_index + 1:
            self.emit("brtrue " + true_label)            # fall through to false
        else:
            self.emit("brtrue " + true_label)
            self.emit("br " + false_label)

    def _stmt_Goto(self, node):
        # GOTO carries no code itself: the branch to its (single) successor block
        # is generated by the block fall-through logic.
        pass

    def _stmt_Rem(self, node):
        # A comment generates no code.
        pass

    def _stmt_End(self, node):
        # Returning from Main ends the program; the template's trailing `ret`
        # also covers a program with no explicit END.
        self.emit("ret")

    # -- expressions --------------------------------------------------------

    def lower_expression(self, node):
        name = type(node).__name__
        if name in _BINARY_OPS:
            self.lower_expression(node.lhs)
            self.lower_expression(node.rhs)
            self.emit(_BINARY_OPS[name])
            return
        if name in _LOGICAL_OPS:
            self.lower_expression(node.lhs)
            self.lower_expression(node.rhs)
            self.emit(_LOGICAL_OPS[name])
            return
        if name in _RELATIONAL_OPS:
            self._lower_relational(node, _RELATIONAL_OPS[name])
            return
        handler = getattr(self, "_expr_" + name, None)
        if handler is None:
            raise CodeGenerationError("Cannot lower expression node %r" % name)
        handler(node)

    def _lower_relational(self, node, opcodes):
        if isinstance(node.lhs.actualType, StringOwlType) or isinstance(
            node.rhs.actualType, StringOwlType
        ):
            # String comparison (String.Compare/Equals) comes later.
            raise CodeGenerationError("string comparison not yet lowered")
        self.lower_expression(node.lhs)
        self.lower_expression(node.rhs)
        for opcode in opcodes:
            self.emit(opcode)

    def _expr_LiteralString(self, node):
        self.emit("ldstr " + _il_string(node.value))

    def _expr_LiteralInteger(self, node):
        self.emit("ldc.i4 %d" % int(node.value))

    def _expr_LiteralFloat(self, node):
        self.emit("ldc.r8 %r" % float(node.value))

    def _expr_Variable(self, node):
        slot = self._local_slot(node.identifier, node.actualType)
        self.emit("ldloc V_%d" % slot)

    def _expr_Cast(self, node):
        # Numeric coercions the type checker inserts (e.g. integer -> float for
        # mixed arithmetic, or assigning an integer to a real variable).
        self.lower_expression(node.value)
        target = node.targetType
        if isinstance(target, FloatOwlType):
            self.emit("conv.r8")
        elif isinstance(target, (IntegerOwlType, ByteOwlType)):
            self.emit("conv.i4")
        else:
            raise CodeGenerationError(
                "Cannot lower cast to %r" % type(target).__name__
            )

    # -- runtime call selection --------------------------------------------

    def _print_call(self, item):
        owl_type = getattr(item, "actualType", None)
        if isinstance(owl_type, StringOwlType):
            arg = "string"
        elif isinstance(owl_type, (IntegerOwlType, ByteOwlType)):
            arg = "int32"
        elif isinstance(owl_type, FloatOwlType):
            arg = "float64"
        else:
            # Fall back to the static node shape when the type is unresolved.
            arg = _arg_from_node(item)
        return "call void {0}::Print({1})".format(_RUNTIME, arg)


def _arg_from_node(node):
    name = type(node).__name__
    if name == "LiteralString":
        return "string"
    if name == "LiteralFloat":
        return "float64"
    # Integers and integer arithmetic.
    return "int32"


_ESCAPES = {"\\": "\\\\", '"': '\\"', "\n": "\\n", "\r": "\\r", "\t": "\\t"}


def _il_string(value):
    """Render a Python string as an ILAsm string literal."""
    out = []
    for ch in value:
        if ch in _ESCAPES:
            out.append(_ESCAPES[ch])
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append("\\%03o" % ord(ch))  # ILAsm octal escape
    return '"' + "".join(out) + '"'
